Repository swyp-web9th-team8/frontend, pull requests merged in 2025-05, with the labels that each got.

#38 Feat: Profile 메인 화면 UI 구현 및 스토리북 등록
  .gitignore
  .storybook/main.ts
  package-lock.json
  src/app/(routes)/profile/page.tsx
  src/assets/icons/IconAddNew.svg
  src/assets/icons/IconChevronRight.svg
  src/assets/icons/IconGroup01.svg
  src/assets/icons/IconLocation.svg
  src/assets/icons/IconMedal01.svg
  src/assets/icons/IconMegaphone.svg
  src/assets/icons/IconSupport.svg
  src/assets/icons/avatar.svg
  src/assets/icons/badge-yellow.svg
  src/components/atoms/InfoBox/InfoBox.tsx
  src/components/molecules/ActivityRow.tsx
  src/components/organisms/profile/ProfileHeader.tsx
  src/components/organisms/profile/SectionWithTitle.tsx
  src/components/templates/.gitkeep
  src/components/templates/ProfilePage.tsx
  src/stories/ActivityRow.stories.tsx
  src/stories/InfoBox.stories.tsx
Labels: enhancement

#36 Feat: Nav 컴포넌트 제작 및 Storybook 설정에 @svgr/webpack 추가
  src/assets/icons/group02.svg
  src/assets/icons/home.svg
  src/assets/icons/medal02.svg
  src/assets/icons/profile.svg
  src/components/organisms/Nav.tsx
  src/stories/Nav.stories.tsx
Labels: enhancement

#40 37/feat completed gathering UI
  package-lock.json
  package.json
  src/app/(routes)/gatherings/[id]/page.tsx
  src/assets/icons/calendar01.svg
  src/assets/icons/clock.svg
  src/assets/icons/location.svg
  src/components/atoms/Badge/GreenBadge.tsx
  src/components/atoms/GatheringImage/GatheringImage.tsx
  src/components/molecules/gatherings/GatheringInfo.tsx
  src/components/molecules/gatherings/ImageCarousel.tsx
  src/components/molecules/gatherings/ParticipantInfo.tsx
  src/components/molecules/gatherings/ParticipantSummary.tsx
  src/components/templates/GatheringCompletedDetail.tsx
  src/stories/GreenBadge.stories.tsx
  src/styles/slick-overrides.css
Labels: enhancement

#42 Feat: Gigantic 폰트 추가 및 Splash·온보딩·회원가입 페이지등 메인 플로우 화면 개편
  public/fonts/Gigantic.ttf
  public/fonts/Gigantic.woff
  public/fonts/Gigantic.woff2
  src/app/(routes)/agreement/page.tsx
  src/app/(routes)/login/page.tsx
  src/app/(routes)/onboarding/page.tsx
  src/app/(routes)/signup/page.tsx
  src/app/(routes)/splash/page.tsx
  src/app/(routes)/welcome/page.tsx
  src/assets/icons/IconAdd.svg
  src/assets/icons/IconExclamation.svg
  src/assets/images/onboarding-page1.svg
  src/assets/images/onboarding-page2.svg
  src/components/atoms/Button/GoogleLoginButton.tsx
  src/components/atoms/Input/FormInput.tsx
  src/components/atoms/Input/GenderSelect.tsx
  src/components/atoms/Input/ProfileImageUploader.tsx
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/AgreementPopup.tsx
  src/components/molecules/RegionSelector.tsx
  src/components/organisms/OnboardingControl.tsx
  src/components/organisms/OnboardingSlide.tsx
  src/constants/onboarding.ts
  src/styles/globals.css
  src/types/onboarding.ts
Labels: enhancement

#45 Feat: 모임 생성 화면에 필요한 Input 구현
  src/app/(routes)/gatherings/create/page.tsx
  src/assets/icons/IconCheck01.svg
  src/assets/icons/IconCheck01Active.svg
  src/assets/icons/IconChevronBelow.svg
  src/components/atoms/Button/ModalButton.tsx
  src/components/atoms/Calendar.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Input/TextArea.tsx
  src/components/atoms/Modal/contents/TwoButtonContents.tsx
  src/components/molecules/Calendar.tsx
  src/components/molecules/DropdownItem.tsx
  src/components/molecules/OverlayView.tsx
  src/components/molecules/TimePicker.tsx
  src/components/molecules/input/InputWithCalendar.tsx
  src/components/molecules/input/InputWithCount.tsx
  src/components/molecules/input/InputWithDropdown.tsx
  src/components/molecules/input/InputWithKaKaoLink.tsx
  src/components/molecules/input/InputWithLabel.tsx
  src/components/molecules/input/InputWithTimePicker.tsx
  src/components/molecules/input/InputWithUnit.tsx
  src/components/organisms/DropdownList.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/constants/createForm.ts
  src/hooks/features/.gitkeep
  src/hooks/features/commons/useModal.ts
  src/hooks/features/useInputWithCalendar.ts
  src/hooks/features/useInputWithDropdown.ts
  src/hooks/features/useInputWithTimePicker.ts
  src/styles/Calendar.module.css
  src/styles/globals.css
  src/types/form.ts
  src/utils/day.ts
Labels: duplicate

#48 Feat: 알림 UI, 공통 컴포넌트(토글, 빈화면) 구현
  src/app/(routes)/notification/layout.tsx
  src/app/(routes)/notification/page.tsx
  src/app/(routes)/notification/settings/page.tsx
  src/app/layout.tsx
  src/assets/icons/IconCheckWithoutCircle.svg
  src/assets/icons/IconChevronLeft.svg
  src/assets/icons/IconExclamation.svg
  src/assets/icons/IconLocation.svg
  src/assets/images/Character.svg
  src/components/atoms/Toggle/Toggle.tsx
  src/components/molecules/notification/NotificationItem.tsx
  src/components/molecules/notification/NotificationSettingsItem.tsx
  src/components/organisms/Empty.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/notification/NotificationList.tsx
  src/components/templates/Notification.tsx
  src/components/templates/NotificationSettings.tsx
  src/data/notification.ts
  src/types/notification.ts
  src/utils/day.ts
Labels: enhancement

#47 Feat: 홈 피드 UI 구현
  src/app/(routes)/home/page.tsx
  src/assets/icons/IconNotification.svg
  src/assets/icons/IconSearch.svg
  src/components/molecules/homegatherings/GatheringCard.tsx
  src/components/molecules/homegatherings/GatheringFilterTabs.tsx
  src/components/organisms/homegatherings/GatheringListGroup.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/data/closedgatherings.ts
  src/data/homegatherings.ts
Labels: enhancement

#51 Feat:리뷰 생성 화면 UI 작업 완료
  src/app/(routes)/review/create/layout.tsx
  src/app/(routes)/review/create/page.tsx
  src/assets/icons/IconAdd.svg
  src/assets/icons/IconClose.svg
  src/components/atoms/Input/ImagesUploader.tsx
  src/components/molecules/input/InputWithModal.tsx
  src/components/molecules/review/AttendanceItem.tsx
  src/components/molecules/review/ReviewCreateItemWithLabel.tsx
  src/components/molecules/review/ReviewSummaryCard.tsx
  src/components/organisms/review/AttendanceList.tsx
  src/components/organisms/review/AttendanceManager.tsx
  src/components/templates/ReviewCreate.tsx
  src/data/attendence.ts
  src/styles/globals.css
  src/types/form.ts
Labels: enhancement

#60 Refactor: Toast 공통 컴포넌트 생성 및 모임 리뷰 화면 리팩토링
  src/app/layout.tsx
  src/assets/icons/IconExclamation.svg
  src/components/atoms/Input/ImagesUploader.tsx
  src/components/molecules/review/ReviewSummaryCard.tsx
  src/components/molecules/toast/Toast.tsx
  src/components/molecules/toast/ToastContext.tsx
  src/components/organisms/review/AttendanceList.tsx
  src/components/organisms/review/AttendanceManager.tsx
  src/components/organisms/review/ReviewCreateButton.tsx
  src/components/templates/ReviewCreate.tsx
  src/data/attendence.ts
  src/data/review.ts
  src/types/form.ts
  src/types/review.ts
Labels: enhancement

#62 Feat: 우편번호 API 연결 및 모임 작성 페이지 리펙토링
  package-lock.json
  package.json
  src/app/(routes)/gatherings/create/layout.tsx
  src/app/layout.tsx
  src/components/atoms/Button/GatheringCreateButton.tsx
  src/components/atoms/Button/ShareButton.tsx
  src/components/atoms/Tooltip/Tooltip.tsx
  src/components/molecules/Calendar.tsx
  src/components/molecules/gatherings/CreateButton.tsx
  src/components/molecules/input/InputWithLabel.tsx
  src/components/molecules/input/InputwithLocation.tsx
  src/components/organisms/DropdownList.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/types/form.ts
Labels: enhancement

#66 Feat: PWA 초기 세팅
  next.config.ts
  package-lock.json
  package.json
  public/manifest.json
  public/sw.js
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
  public/web-app-manifest-screenshot-1.png
  public/workbox-4754cb34.js
  src/app/layout.tsx
Labels: enhancement

#72 Feat: 회원가입 요청 API 연동 및 지역 데이터 axios 처리
  public/sw.js
  public/workbox-4754cb34.js
  public/workbox-e43f5367.js
  src/api/auth/getMyProfile.ts
  src/app/(routes)/login/page.tsx
  src/app/(routes)/signup/page.tsx
  src/components/atoms/Button/SubmitButton.tsx
  src/components/atoms/Input/ProfileImageUploader.tsx
  src/components/atoms/Tooltip/Tooltip.tsx
  src/components/molecules/RegionSelectorForm.tsx
  src/components/organisms/SignupForm.tsx
  src/components/pages/oauth/OauthCallbackClient.tsx
  src/hooks/mutations/useOauthLogin.tsx
  src/hooks/queries/.gitkeep
  src/hooks/queries/useSignup.ts
  src/lib/axiosInstance.ts
  src/stores/useAuthStore.ts
Labels: enhancement

#76 Feat:: 모임 생성 API 연결 및 리뷰 독촉 API 연결
  .gitignore
  public/sw.js
  public/workbox-4754cb34.js
  src/api/auth/getMyProfile.ts
  src/api/gatherings/gatherings.ts
  src/api/gatherings/review.ts
  src/api/oauth/google.ts
  src/api/oauth/kakao.ts
  src/components/pages/oauth/OauthCallbackClient.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/hooks/queries/useCreateGathering.ts
  src/hooks/queries/useReview.ts
  src/lib/axiosInstance.ts
  src/types/gatherings.ts
  src/utils/day.ts
Labels: enhancement

#80 Feat: 모임 섹션 리팩토링
  package-lock.json
  package.json
  src/api/gatherings/gatherings.ts
  src/api/gatherings/review.ts
  src/app/(routes)/gatherings/recruiting/[id]/page.tsx
  src/app/(routes)/home/page.tsx
  src/app/layout.tsx
  src/assets/icons/IconExclamationGreen.svg
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/gatherings/ImageCarousel.tsx
  src/components/molecules/input/InputWithDropdown.tsx
  src/components/molecules/input/InputWithKaKaoLink.tsx
  src/components/molecules/input/InputwithLocation.tsx
  src/components/molecules/toast/ToastContext.tsx
  src/components/organisms/DropdownList.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/header/RecruitingDetailHeader.tsx
  src/components/organisms/modal/ReConfirm.tsx
  src/components/organisms/modal/ReConfirmModalContext.tsx
  src/components/organisms/modal/ReviewConfirmModal.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/components/templates/ReviewCreate.tsx
  src/components/templates/gatheringRecruiting.tsx
  src/hooks/features/commons/useGeoLocation.ts
  src/hooks/features/commons/useIntersectionObserver.ts
  src/hooks/features/commons/useOutsideClick.ts
  src/hooks/features/useInputWithDropdown.ts
  src/hooks/mutations/useReview.ts
  src/hooks/queries/useCreateGathering.ts
  src/hooks/queries/useFetchGatheringDetail.ts
  src/hooks/queries/useFetchGatheringList.ts
  src/hooks/queries/useReview.ts
  src/types/form.ts
  src/types/gatherings.ts
  src/utils/day.ts
Labels: enhancement

#83 Feat: 모임 상세 조회, 리뷰 작성, 리뷰 독촉 API 연결
  next.config.ts
  src/api/gatherings/review.ts
  src/app/(routes)/gatherings/[id]/layout.tsx
  src/app/(routes)/gatherings/[id]/page.tsx
  src/app/(routes)/gatherings/completed/layout.tsx
  src/app/(routes)/gatherings/completed/page.tsx
  src/app/(routes)/gatherings/page.tsx
  src/app/(routes)/gatherings/recruiting/[id]/page.tsx
  src/app/(routes)/review/create/layout.tsx
  src/components/atoms/Input/ImagesUploader.tsx
  src/components/molecules/gatherings/GatheringInfo.tsx
  src/components/molecules/gatherings/ParticipantSummary.tsx
  src/components/molecules/recruiting/Description.tsx
  src/components/molecules/recruiting/JoinButton.tsx
  src/components/molecules/recruiting/ParticipantSummary.tsx
  src/components/molecules/recruiting/RecruitingSummary.tsx
  src/components/molecules/review/ReviewSummaryCard.tsx
  src/components/organisms/header/CompletedGatheringHeader.tsx
  src/components/organisms/header/CreateReviewHeader.tsx
  src/components/organisms/review/AttendanceList.tsx
  src/components/organisms/review/AttendanceManager.tsx
  src/components/templates/GatheringCompletedDetail.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/components/templates/ReviewCreate.tsx
  src/components/templates/gatheringRecruiting.tsx
  src/constants/createForm.ts
  src/hooks/mutations/useReview.ts
  src/hooks/queries/useFetchGatheringDetail.ts
  src/hooks/queries/useFetchGatheringList.ts
  src/types/form.ts
  src/types/gatherings.ts
  src/utils/day.ts
Labels: enhancement

#84 Feat: 홈 피드 화면 모임 화면 출력 및 지역 선택에 따른 조회 파라미터 변경
  src/api/gatherings/gatherings.ts
  src/app/(routes)/home/page.tsx
  src/components/molecules/homefeed/LocationSelectorDropdown.tsx
  src/components/molecules/homegatherings/GatheringCard.tsx
  src/components/organisms/gatherings/GatheringItem.tsx
  src/components/organisms/homegatherings/GatheringListGroup.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/data/closedgatherings.ts
  src/data/gatherings.ts
  src/data/homegatherings.ts
  src/hooks/queries/useFetchGatheringList.ts
  src/hooks/queries/useParticipateGathering.ts
  src/lib/axiosInstance.ts
  src/types/gatherings.ts
  src/utils/auth.ts
  src/utils/day.ts
Labels: enhancement

#88 Feat: 완료된 모임 목록 / 상세 조회 연결
  src/api/gatherings/gatherings.ts
  src/app/(routes)/gatherings/completed/[id]/layout.tsx
  src/app/(routes)/gatherings/completed/layout.tsx
  src/app/(routes)/gatherings/completed/page.tsx
  src/app/(routes)/home/layout.tsx
  src/components/organisms/Nav.tsx
  src/components/organisms/gatherings/GatheringList.tsx
  src/components/templates/GatheringCompletedTemplate.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/hooks/queries/useFetchGatheringList.ts
  src/styles/globals.css
  src/types/gatherings.ts
Labels: enhancement

#90 Refactor: 완료된 모임 / 상세 완료된 모임 API 수정
  next.config.ts
  src/app/(routes)/gatherings/[id]/layout.tsx
  src/app/(routes)/gatherings/completed/[id]/layout.tsx
  src/app/(routes)/gatherings/completed/[id]/page.tsx
  src/app/(routes)/gatherings/completed/layout.tsx
  src/app/(routes)/gatherings/recruiting/[id]/layout.tsx
  src/app/(routes)/home/layout.tsx
  src/app/(routes)/ranking/layout.tsx
  src/app/(routes)/ranking/page.tsx
  src/app/layout.tsx
  src/app/providers/ReactQueryProviders.tsx
  src/components/atoms/Button/GatheringCreateButton.tsx
  src/components/atoms/Button/ShareButton.tsx
  src/components/atoms/Input/ImagesUploader.tsx
  src/components/molecules/input/InputWithDropdown.tsx
  src/components/molecules/participant/ParticipantImageWithText.tsx
  src/components/molecules/profile/ProfileImageUploader.tsx
  src/components/organisms/Nav.tsx
  src/components/organisms/gatherings/GatheringItem.tsx
  src/components/organisms/gatherings/GatheringList.tsx
  src/components/organisms/header/RecruitingDetailHeader.tsx
  src/components/organisms/profile/ProfileHeader.tsx
  src/components/templates/GatheringCompletedTemplate.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/hooks/queries/useFetchGatheringList.ts
  src/types/gatherings.ts
Labels: enhancement

#92 Fix: 회원가입 창 이미지 노출 / 랭킹 API 조회 연결 / 요청 참여, 나가기 API 수정 등
  next.config.ts
  src/api/gatherings/gatherings.ts
  src/api/ranking/ranking.ts
  src/app/(routes)/gatherings/completed/layout.tsx
  src/app/(routes)/gatherings/completed/page.tsx
  src/app/(routes)/profile/page.tsx
  src/app/(routes)/ranking/page.tsx
  src/components/atoms/Input/ImagesUploader.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Input/ProfileImageUploader.tsx
  src/components/molecules/gatherings/ParticipantSummary.tsx
  src/components/molecules/homegatherings/GatheringCard.tsx
  src/components/molecules/input/InputWithModal.tsx
  src/components/molecules/participant/ParticipantImageWithText.tsx
  src/components/molecules/recruiting/JoinButton.tsx
  src/components/organisms/gatherings/GatheringItem.tsx
  src/components/organisms/review/ReviewCreateButton.tsx
  src/components/templates/RankingTemplate.tsx
  src/components/templates/ReviewCreate.tsx
  src/components/templates/gatheringRecruiting.tsx
  src/hooks/queries/useParticipateGathering.ts
  src/hooks/queries/useRanking.ts
  src/hooks/queries/useSignup.ts
  src/stores/useAuthStore.ts
  src/types/form.ts
  src/types/ranking.ts
Labels: enhancement

#94 Feat/93 ranking UI
  src/app/(routes)/ranking/layout.tsx
  src/components/molecules/homegatherings/GatheringCard.tsx
  src/components/molecules/recruiting/JoinButton.tsx
  src/components/organisms/ranking/RankingItem.tsx
  src/components/organisms/ranking/RankingList.tsx
  src/components/organisms/ranking/RankingTap.tsx
  src/components/organisms/ranking/Top3RankingItem.tsx
  src/components/organisms/ranking/Top3RankingList.tsx
  src/components/templates/RankingTemplate.tsx
  src/hooks/queries/useParticipateGathering.ts
  src/hooks/queries/useRanking.ts
Labels: enhancement

#98 Fix: 서울 외 지역에 대한 에러처리
  src/components/molecules/homefeed/LocationSelectorDropdown.tsx
  src/constants/errorMessage.ts
Labels: bug

#99 Feat: 랭킹 페이지 이미지 사이즈 수정 및 이미지 에러 처리
  next.config.ts
  src/components/atoms/ProfileImage/ProfileImage.tsx
  src/components/molecules/profile/ProfileImageUploader.tsx
  src/components/organisms/profile/EditProfileForm.tsx
  src/components/organisms/profile/ProfileHeader.tsx
  src/hooks/mutations/useUpdateProfileImage.ts
  src/utils/useImageUrl.ts
Labels: bug

#100 Fix: 상태관리를 통한 이미지 로딩 실패 추적
  src/components/atoms/ProfileImage/ProfileImage.tsx
Labels: bug

#101 Fix: 프로필 이미지 속성 추가
  src/components/atoms/ProfileImage/ProfileImage.tsx
  src/components/organisms/profile/ProfileHeader.tsx
  src/components/templates/HomeFeedTemplate.tsx
Labels: bug

#102 Feat: 모임 작성 모달 변경
  src/components/atoms/GatheringImage/GatheringImage.tsx
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/gatherings/ImageCarousel.tsx
  src/components/organisms/modal/GatheringCreateConfirmModal.tsx
  src/components/organisms/modal/ReConfirmModalContext.tsx
  src/components/organisms/modal/ReviewConfirmModal.tsx
  src/components/templates/GatheringCompletedDetail.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/constants/createForm.ts
  src/hooks/queries/useCreateGathering.ts
  src/types/gatherings.ts
Labels: enhancement

#103 Fix: 모임 만들기 경로 수정 및 홈 피드 화면 클릭 이벤트 해결
  src/app/(routes)/profile/mygathering/page.tsx
  src/components/templates/HomeFeedTemplate.tsx
Labels: enhancement

#106 Fix: 프로필 이미지 quality수정
  src/components/molecules/profile/ProfileImageUploader.tsx
  src/components/organisms/profile/EditProfileForm.tsx
  src/utils/useImageUrl.ts
Labels: bug

#108 fix: 닉네임 수정 버튼 레이아웃 수정
  src/components/organisms/profile/ProfileHeader.tsx
  src/components/templates/EditNicknameTemplate.tsx
Labels: bug

#109 Fix: ranking number
  src/app/(routes)/gatherings/completed/page.tsx
  src/app/(routes)/home/layout.tsx
  src/assets/icons/Loading.svg
  src/assets/icons/rank1.svg
  src/assets/icons/rank2.svg
  src/assets/icons/rank3.svg
  src/components/molecules/homegatherings/GatheringFilterTabs.tsx
  src/components/organisms/Nav.tsx
  src/components/organisms/gatherings/GatheringList.tsx
  src/components/organisms/modal/GatheringCreateConfirmModal.tsx
  src/components/organisms/modal/ReConfirm.tsx
  src/components/organisms/modal/ReviewConfirmModal.tsx
  src/components/organisms/ranking/RankingItem.tsx
  src/components/organisms/ranking/Top3RankingItem.tsx
  src/components/pages/oauth/OauthCallbackClient.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/components/templates/RankingTemplate.tsx
  src/components/templates/ReviewCreate.tsx
  src/types/ranking.ts
  src/utils/day.ts
  src/utils/gatherings.ts
Labels: bug

#115 Fix: FAB 버튼 등 수정
  src/app/(routes)/gatherings/recruiting/[id]/layout.tsx
  src/app/(routes)/ranking/layout.tsx
  src/app/layout.tsx
  src/components/atoms/Button/GatheringCreateButton.tsx
  src/components/atoms/Button/ShareButton.tsx
  src/components/organisms/header/RecruitingDetailHeader.tsx
  src/constants/errorMessage.ts
  src/hooks/queries/useCreateGathering.ts
  src/hooks/queries/useFetchGatheringList.ts
  src/styles/globals.css
  src/types/gatherings.ts
Labels: bug, enhancement

#116 Fix: min-h-screen 으로 변경
  src/app/layout.tsx
Labels: bug

#120 Fix: 모임 목록 조회(홈 피드, 모임 메뉴)에 무한 스크롤 적용되지 않았던 문제 해결
  src/components/organisms/gatherings/GatheringList.tsx
  src/components/templates/GatheringsCreatePage.tsx
  src/components/templates/HomeFeedTemplate.tsx
  src/components/templates/ProfilePage.tsx
  src/hooks/queries/useFetchGatheringList.ts
Labels: bug

#123 Fix/modal modify
  src/components/atoms/Button/ModalButton.tsx
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/Modal/contents/TwoButtonContents.tsx
  src/components/molecules/input/InputWithCalendar.tsx
  src/components/molecules/input/InputWithKaKaoLink.tsx
  src/components/molecules/input/InputWithTimePicker.tsx
  src/components/organisms/region/RegionPicker.tsx
  src/styles/Calendar.module.css
Labels: enhancement

#124 Fix: 공통 Modal의 패딩을 제거하고, 각 컴포넌트에서 패딩을 부여
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/RegionSelectorModal.tsx
  src/components/molecules/input/InputWithModal.tsx
  src/components/organisms/region/RegionPicker.tsx
Labels: bug
